### PR TITLE
Crypto/AES_256_CBC: Generate iv before encryption and decryption

### PR DESCRIPTION
**Pull request by RoxasShadow**
According to #2.

Many tests are waiting on the horizon :dancer:

### CODE REVIEW

**Comment by dchest** [comment]
Looks good, but length check should be corrected, I think: minimum encrypted file size is 32 (16-byte iv + 16-byte one padded block).

**Comment by RoxasShadow** [comment]
Considering #9:

```ruby
rbx-2.5.8 :003 > EDB::Cryptography::AES_256_CBC.encrypt 'kk'
 => "\xF8\x1E\x8D\xD2\xD7\xFF\x9F\x12\xF7l\xB4\xB4>u\xFF\xB7\xE9\xDDs\xBFEWu\xC7B\xC5q\x86\xD6\xA5\a\x10 \xCFg\xC6\x8B\x14\x10\r*\x01\xAB\xABk \x99\xE4.\x92_\x1D" 
rbx-2.5.8 :004 > EDB::Cryptography::AES_256_CBC.decrypt _
 => "kk" 
```

`iv.length #=> 16` while `authentication.length #=> 20`

**Comment by RoxasShadow** [comment]
You're right, I forgot that.

**Comment by dchest** [comment]
CBC mode contains minimum one cipher block, in case of AES it's 16 bytes. Plus IV is 16 bytes. Plus HMAC, which if you choose SHA256 instead of SHA1 will be 32 bytes, so it's 64 bytes min.

**Comment by RoxasShadow** [comment]
Seems good. I pushed the changes to #9.

**Pull request merged**
