### PR TITLE
Crypto/AES_256_CBC: Add decryption in the executable and authenticate the ciphering

### PR DESCRIPTION
**Pull request by RoxasShadow**
According to #1.

### CODE REVIEW

**Comment by dchest** [comment]
Please use HMAC-SHA256 for authentication, SHA-1 should no longer be used for crypto purposes.

**Comment by dchest** [comment]
:+1: 

You don't need to make the key longer than 32 bytes, but it won't hurt.

**Comment by RoxasShadow** [comment]
Are you referring to the ones generated by the `#hash_keychain`? Let's do 64 then, it won't be a problem.

**Comment by dchest** [comment]
I was talking about authentication key — it's fine if it's 32 or 64 bytes. But now I see that even encryption key is 64 bytes — strange that OpenSSL doesn't throw error in this case — AES supports 16, 20 or 32 byte keys (AES-256 = 32 byte key), why did it even accept 64 bytes? Does it throw away the other bytes?

**Comment by RoxasShadow** [comment]
Yes, I just made a test with the encryption key both long 32 and 64 bytes and the output is the same, so I guess it just throws away the last 32 bytes :+1:

**Comment by dchest** [comment]
OK. I'd suggest to bring the encryption one back to 32 bytes to avoid confusion.

**Comment by RoxasShadow** [comment]
Do you mean authentication key? Because I was going to set the encryption key to 32 bytes and the authentication key to 64 bytes.

**Comment by dchest** [comment]
No, the encryption key.

>  Because I was going to set the encryption key to 32 bytes and the authentication key to 64 bytes.

Yes, that's what I was talking about :+1:

**Comment by RoxasShadow** [comment]
Great then, committed at 63c2a02 and 110cc14 (that little method was a little dangerous).

**Comment by dchest** [comment]
Nice, looks clearer now.

**Pull request merged**
